services:

  polaris-bootstrap:
    image: apache/polaris-admin-tool:1.2.0-incubating
    environment:
      - POLARIS_PERSISTENCE_TYPE=relational-jdbc
      - QUARKUS_DATASOURCE_JDBC_URL=${QUARKUS_DATASOURCE_JDBC_URL}
      - QUARKUS_DATASOURCE_USERNAME=${QUARKUS_DATASOURCE_USERNAME}
      - QUARKUS_DATASOURCE_PASSWORD=${QUARKUS_DATASOURCE_PASSWORD}
    command:
      - "bootstrap"
      - "--realm=${POLARIS_REALM}"
      - "--credential=${POLARIS_REALM},${POLARIS_CLIENT_ID},${POLARIS_SECRET}"
    depends_on:
      postgres:
        condition: service_healthy

  polaris:
    image: apache/polaris:1.2.0-incubating
    ports:
      - "8181:8181"
      - "8182:8182"
    environment:
      JAVA_DEBUG: true
      POLARIS_PERSISTENCE_TYPE: relational-jdbc
      POLARIS_PERSISTENCE_RELATIONAL_JDBC_MAX_RETRIES: 5
      POLARIS_PERSISTENCE_RELATIONAL_JDBC_INITIAL_DELAY_IN_MS: 100
      POLARIS_PERSISTENCE_RELATIONAL_JDBC_MAX_DURATION_IN_MS: 5000
      QUARKUS_DATASOURCE_JDBC_URL: $QUARKUS_DATASOURCE_JDBC_URL
      QUARKUS_DATASOURCE_USERNAME: $QUARKUS_DATASOURCE_USERNAME
      QUARKUS_DATASOURCE_PASSWORD: $QUARKUS_DATASOURCE_PASSWORD
      QUARKUS_LOG_LEVEL: INFO
      QUARKUS_LOG_CONSOLE_JSON_ENABLED: true
      QUARKUS_LOG_FILE_JSON_ENABLED: true
      POLARIS_REALM_CONTEXT_REALMS: $POLARIS_REALM
      QUARKUS_OTEL_SDK_DISABLED: true
      POLARIS_BOOTSTRAP_CREDENTIALS: POLARIS,$POLARIS_CLIENT_ID,$POLARIS_SECRET
      polaris.features."ALLOW_INSECURE_STORAGE_TYPES": "true"
      polaris.features."SUPPORTED_CATALOG_STORAGE_TYPES": "[\"FILE\",\"S3\",\"GCS\",\"AZURE\"]"
      polaris.readiness.ignore-severe-issues: "true"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8182/q/health"]
      interval: 2s
      timeout: 10s
      retries: 10
      start_period: 10s
    depends_on:
      polaris-bootstrap:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy

  polaris-setup:
    image: alpine/curl
    environment:
      # - STORAGE_LOCATION=${STORAGE_LOCATION}
      # - AWS_ROLE_ARN=${AWS_ROLE_ARN}
      # - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      REALM: $POLARIS_REALM
      CLIENT_ID: $POLARIS_CLIENT_ID
      CLIENT_SECRET: $POLARIS_SECRET
      CATALOG_NAME: $ICEBERG_CATALOG_NAME
    volumes:
      - ${ASSETS_PATH}/polaris/:/polaris
    entrypoint: '/bin/sh -c "chmod +x /polaris/create-catalog.sh && /polaris/create-catalog.sh"'
    depends_on:
      polaris:
        condition: service_healthy