services:

  # unity_catalog:
  #   image: unitycatalog/unitycatalog:latest
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - type: bind
  #       source: ${ASSETS_PATH}/unity
  #       target: /opt/unitycatalog/etc/conf
  #     - type: volume
  #       source: unitycatalog_data
  #       target: /opt/unitycatalog/etc/data

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${UNITY_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres

volumes:
  # Persist docker volume across container restarts
  postgres_data: